### ISSUE TITLE
Is it possible to specify the expected type of a parameter?

### ISSUE THREAD

**Issue by npoirey** [Feneric/doxypypy#12]
Hello,
I'm new to python and I've been trying to use doxygen with doxypypy.

So far, it works as I expected, but i wonder if there is a way to show the expected type of an incoming parameter or return value so that it's correctly interpreted by doxygen afterward ?

Thank you

**Comment by raabf** [comment]
If I understand that right doxygen will always try to get the type from the function signature, so manually specifying is not possible.
Hopefully they will [implement the Function Annotations like requested](https://bugzilla.gnome.org/show_bug.cgi?id=748758) to have the ability to document the type.
