### ISSUE TITLE
"Definition at line" does not work correctly

### ISSUE THREAD

**Issue by DevynCJohnson** [Feneric/doxypypy#27]
I am using your doxypypy filter (thanks for this filter) with my Doxygen documentation for my PyBooster project (here on GitHub). However, when I click "Definition at line 883", I am taken to the page containing the src, but I am not taken to the line specified. The URL does show the parameter for the line (basic_8py_source.html#l00883). The "Definition at line XXX" works with the documentation of my C code, but after using doxypypy, the "Definition at line XXX" does not work with the Python code (as it did prior to using doxypypy).

**Comment by DevynCJohnson** [comment]
After further investigation, I noticed that it does work for some functions. Specifically, this fails to work properly with functions using Type-Hints ([PEP0484](https://www.python.org/dev/peps/pep-0484/)).

Example of a function using Type-Hints:
`def getwebpage(_address: str) -> str:`

**Comment by Feneric** [comment]
Getting an exact match of line numbers is likely never to work without some additional support from Doxygen. The doxypypy filter changes Python source, adding Doxygen tags where necessary to communicate intent to Doxygen. It minimizes changing line count, but cannot eliminate it 100% of the time. Doxygen doesn't have the facility for a filter to provide an "original line number" tag or the like, so anytime line count gets changed the links will drift. This isn't just a problem for doxypypy, it's a problem for any Doxygen filter that has to change line count. Right now the official Doxygen recommendation appears to be not to change line count at all, but the more the source language differs from Java the more line count needs to get changed to produce proper documentation.

**Comment by DevynCJohnson** [comment]
Okay. Thanks anyway.
