### ISSUE TITLE
Importing 'linesep' from 'os' leeds to every other line being blank in Windows

### ISSUE THREAD

**Issue by cfrings** [Feneric/doxypypy#52]
See: [https://stackoverflow.com/questions/21636213/why-you-shouldnt-use-os-linesep-when-editing-on-text-mode](https://stackoverflow.com/questions/21636213/why-you-shouldnt-use-os-linesep-when-editing-on-text-mode)

This then breaks doxygen's comment parsing.

Defining `linesep` as `\n` works.

**Comment by burgerbecky** [comment]
I've tested this, changing linesep to \n works on Linux, Mac and Windows.

**Comment by burgerbecky** [comment]
I've created a Pull Request on this issue, since I have the same problem.

**Comment by Feneric** [comment]
Fixed.
