### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by magwas** [Feneric/doxypypy#65]
Where are the instructions/code on how to test?
I have seen no mention of it in the README, no CODING file, setup.py does not seem to contain anything related, no .travis.yml, shippable.yml, Makefile, or anything like that.
Running unittest with discovery fails.
Running `PYTHONPATH=. ./doxypypy/test/test_doxypypy.py` fails a lot of tests with `AttributeError: 'Options' object has no attribute 'object_respect'`

**Comment by magwas** [comment]
dropped doxypypy from my toolchain.

**Comment by Feneric** [comment]
They're ordinary Python unit tests. They should be runnable via direct call or as a module. Modernizing the testing is pretty high up on my list of what I'd personally like to see for doxypypy.

I'm sorry it didn't work out for you.
