### ISSUE TITLE
Update package on PyPi 

### ISSUE THREAD

**Issue by rynkk** [Feneric/doxypypy#81]
The package distributed by PyPi seems to be outdated. The current version is from May 23, 2015.
Important fixes like c0e95e4c3ecec10da9de00adae0d77bc52f3933f are not included there.

It might be sensible to bump the version number and update the package on PyPi.

**Comment by Feneric** [comment]
I'd like to try and work in a few more of the fixes that have been provided first, but they all have their own issues / lack tests / etc. and I've not had the time to address them. Any help is appreciated, but we are trying to ensure that doxypypy is pretty well tested and that features have associated tests.

**Comment by Feneric** [comment]
I'm looking to do so in the near future. I was trying to get a few fixes in / few pull requests in first, but unfortunately most are just me (in the former case) and just me providing tests (in the latter case) so it'll be when I can do it. Fixes with tests are hugely appreciated!

**Comment by Feneric** [comment]
The PyPi version now reflects the latest & greatest here in GitHub.
